Pin the inkwell version to latest stable on master
jamesmth/llvm-plugin-rs pull request #11
Opened 2024-07-06 08:12 UTC by AdityaAtulTewari

The current master branch of inkwell seems to change a lot and for compatibility issues it might help to pin the revision.

I was having trouble building this as well because the macro for `llvm_versions` now uses different syntax so I fixed that as well.

Please let me know what steps I can take to help get this merged, I really like the idea of this tool and this allows me to use it for my research.

2024-07-08 06:55 UTC, jamesmth approved these changes
You are right, we should pin to a specific commit, I overlooked that!

Looks good to me!

2024-07-08 07:12 UTC, jamesmth commented
Most MacOS tests failed and some Linux tests failed as well.

For MacOS, it seems that https://github.com/TheDan64/inkwell/commit/5c9f7fcbb0a667f7391b94beb65f1a670ad13221 fixes the issue. For Linux, however, we may have to pin to a an older commit (which would not break on MacOS either).

2024-07-08 07:15 UTC, jamesmth requested changes
You are right, we should pin to a specific commit, I overlooked that!

Most MacOS tests failed and some Linux tests failed as well.

For MacOS, it seems that https://github.com/TheDan64/inkwell/commit/5c9f7fcbb0a667f7391b94beb65f1a670ad13221 fixes the issue. For Linux, however, we may have to pin to a an older commit (which would not break on MacOS either).

2024-07-13 19:58 UTC, AdityaAtulTewari commented
Cool I'll start the search from there thanks!

2024-07-13 22:14 UTC, AdityaAtulTewari commented
is there some sort of docker style tests for this? the different linux instances/would you be opposed to introducing that so I can build the linux builds locally?

2024-07-14 08:42 UTC, jamesmth commented
There are no docker images for testing the Linux builds, since I wanted to keep the CI workflow similar between MacOS, Windows and Linux.

If you look at the `.github/workflows/linux.yml` file, you can reproduce the Linux test locally with a few commands. Running the test 4 (which fails) with llvm-12 for instance:
```bash
$ wget -O llvm.tar.gz https://github.com/jamesmth/llvm-project/releases/download/v12.0.1-rust-1.55/llvm-lld-12.0.1-rust-1.55-linux-x86_64.tar.gz
$ tar xf llvm.tar.gz
$ LLVM_SYS_120_PREFIX=$PWD/llvm cargo b --manifest-path tests/plugins/Cargo.toml -p plugin* --no-default-features --features target-x86,llvm12-0
$ llvm/bin/opt --load-pass-plugin="tests/plugins/target/debug/libplugin4.so" --passes="mpass,function(fpass)" tests/test.ll -disable-output
```

2024-07-14 09:06 UTC, jamesmth commented
Anyway, I fixed the issue with Linux tests with the following modifications:

Replacing these lines:
https://github.com/jamesmth/llvm-plugin-rs/blob/31cc6f2fc50f99e6b35edf8145a52292fba4a427/llvm-plugin/src/analysis.rs#L74-L81

With:
```rust
let res = crate::get_function_analysis_cached_result(
     self.inner,
     id,
     function.as_value_ref().cast(),
);

if !res.is_null() {
    let res = unsafe { Box::leak(Box::from_raw(res.cast())) };
    Some(res)
} else {
    None
}}
```

And replacing this line:
https://github.com/jamesmth/llvm-plugin-rs/blob/31cc6f2fc50f99e6b35edf8145a52292fba4a427/llvm-plugin/src/analysis.rs#L217

With:
```rust
if !res.is_null() {
    let res = unsafe { Box::leak(Box::from_raw(res.cast())) };
    Some(res)
} else {
    None
}
```

If you apply these changes it should pass the CI tests (hopefully).

2024-07-14 09:16 UTC, jamesmth requested changes

2024-07-14 09:16 UTC, jamesmth commented on llvm-plugin/Cargo.toml
> +inkwell_internals = { git = "https://github.com/TheDan64/inkwell", rev = "5c9f7fc"" }
```suggestion
inkwell_internals = { git = "https://github.com/TheDan64/inkwell", rev = "5c9f7fc" }
```

2024-07-15 07:35 UTC, jamesmth requested changes
Just apply `rustfmt` and we are good to merge!

2024-07-15 11:38 UTC, jamesmth approved these changes

2024-07-15 11:39 UTC, merged